import { MeshReflectorMaterial, useGLTF } from "@react-three/drei";

const City = (props) => {
  const { nodes, materials } = useGLTF("/model/city.glb");

  return (
    <group {...props} dispose={null} rotation-x={30}>
      <mesh
        castShadow
        geometry={nodes.Box74.geometry}
        material={nodes.Box74.material}
      />
      <mesh
        castShadow
        geometry={nodes.Line16.geometry}
        material={nodes.Line16.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box122.geometry}
        material={nodes.Box122.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box75.geometry}
        material={nodes.Box75.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box134.geometry}
        material={nodes.Box134.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box77.geometry}
        material={nodes.Box77.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box133.geometry}
        material={nodes.Box133.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box132.geometry}
        material={nodes.Box132.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box121.geometry}
        material={nodes.Box121.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box126.geometry}
        material={nodes.Box126.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box128.geometry}
        material={nodes.Box128.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box127.geometry}
        material={nodes.Box127.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box120.geometry}
        material={nodes.Box120.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box125.geometry}
        material={nodes.Box125.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box124.geometry}
        material={nodes.Box124.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box105.geometry}
        material={nodes.Box105.material}
      />
      <mesh
        castShadow
        material={nodes.Box106.material}
        geometry={nodes.Box106.geometry}
      />

      <mesh
        castShadow
        geometry={nodes.Box107.geometry}
        material={nodes.Box107.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box108.geometry}
        material={nodes.Box108.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box109.geometry}
        material={nodes.Box109.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box110.geometry}
        material={nodes.Box110.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box111.geometry}
        material={nodes.Box111.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box112.geometry}
        material={nodes.Box112.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box113.geometry}
        material={nodes.Box113.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box114.geometry}
        material={nodes.Box114.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box115.geometry}
        material={nodes.Box115.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box116.geometry}
        material={nodes.Box116.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box117.geometry}
        material={nodes.Box117.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box118.geometry}
        material={nodes.Box118.material}
      />
      <mesh
        castShadow
        geometry={nodes.Building_3.geometry}
        material={nodes.Building_3.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box02.geometry}
        material={nodes.Box02.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box01.geometry}
        material={nodes.Box01.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box03.geometry}
        material={nodes.Box03.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box04.geometry}
        material={nodes.Box04.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box05.geometry}
        material={nodes.Box05.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box06.geometry}
        material={nodes.Box06.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box07.geometry}
        material={nodes.Box07.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box08.geometry}
        material={nodes.Box08.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box09.geometry}
        material={nodes.Box09.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box10.geometry}
        material={nodes.Box10.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box11.geometry}
        material={nodes.Box11.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box12.geometry}
        material={nodes.Box12.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box13.geometry}
        material={nodes.Box13.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box14.geometry}
        material={nodes.Box14.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box28.geometry}
        material={nodes.Box28.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box29.geometry}
        material={nodes.Box29.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box30.geometry}
        material={nodes.Box30.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box31.geometry}
        material={nodes.Box31.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box32.geometry}
        material={nodes.Box32.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box33.geometry}
        material={nodes.Box33.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box34.geometry}
        material={nodes.Box34.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box35.geometry}
        material={nodes.Box35.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box36.geometry}
        material={nodes.Box36.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box37.geometry}
        material={nodes.Box37.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box38.geometry}
        material={nodes.Box38.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box39.geometry}
        material={nodes.Box39.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box15.geometry}
        material={nodes.Box15.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box16.geometry}
        material={nodes.Box16.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box17.geometry}
        material={nodes.Box17.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box18.geometry}
        material={nodes.Box18.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box19.geometry}
        material={nodes.Box19.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box20.geometry}
        material={nodes.Box20.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box21.geometry}
        material={nodes.Box21.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box22.geometry}
        material={nodes.Box22.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box23.geometry}
        material={nodes.Box23.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box24.geometry}
        material={nodes.Box24.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box25.geometry}
        material={nodes.Box25.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box26.geometry}
        material={nodes.Box26.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box27.geometry}
        material={nodes.Box27.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box46.geometry}
        material={nodes.Box46.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box47.geometry}
        material={nodes.Box47.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box48.geometry}
        material={nodes.Box48.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box49.geometry}
        material={nodes.Box49.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box50.geometry}
        material={nodes.Box50.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box51.geometry}
        material={nodes.Box51.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box52.geometry}
        material={nodes.Box52.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box53.geometry}
        material={nodes.Box53.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box54.geometry}
        material={nodes.Box54.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box55.geometry}
        material={nodes.Box55.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box56.geometry}
        material={nodes.Box56.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box57.geometry}
        material={nodes.Box57.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box58.geometry}
        material={nodes.Box58.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box59.geometry}
        material={nodes.Box59.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box60.geometry}
        material={nodes.Box60.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box61.geometry}
        material={nodes.Box61.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box62.geometry}
        material={nodes.Box62.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box63.geometry}
        material={nodes.Box63.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box64.geometry}
        material={nodes.Box64.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box65.geometry}
        material={nodes.Box65.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box66.geometry}
        material={nodes.Box66.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box67.geometry}
        material={nodes.Box67.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box68.geometry}
        material={nodes.Box68.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box69.geometry}
        material={nodes.Box69.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box70.geometry}
        material={nodes.Box70.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box129.geometry}
        material={nodes.Box129.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box130.geometry}
        material={nodes.Box130.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box131.geometry}
        material={nodes.Box131.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box119.geometry}
        material={nodes.Box119.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box123.geometry}
        material={nodes.Box123.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box86.geometry}
        material={nodes.Box86.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box85.geometry}
        material={nodes.Box85.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box84.geometry}
        material={nodes.Box84.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box83.geometry}
        material={nodes.Box83.material}
      />
      <mesh
        castShadow
        geometry={nodes.Line12.geometry}
        material={nodes.Line12.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box82.geometry}
        material={nodes.Box82.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box81.geometry}
        material={nodes.Box81.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box79.geometry}
        material={nodes.Box79.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box78.geometry}
        material={nodes.Box78.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box76.geometry}
        material={nodes.Box76.material}
      />
      <mesh
        castShadow
        geometry={nodes.Box80.geometry}
        material={nodes.Box80.material}
      />
      <mesh
        castShadow
        geometry={nodes.Building_21.geometry}
        material={nodes.Building_21.material}
      />
      <mesh
        receiveShadow
        geometry={nodes.Box228.geometry}
        //material={nodes.Box228.material}
      >
        <MeshReflectorMaterial
          roughness={0.8}
          distortion={0.1}
          opacity={1}
          color={"rgb(175, 175, 175)"}
        />
      </mesh>
      <points
        geometry={nodes.mesh_112.geometry}
        material={nodes.mesh_112.material}
      />
    </group>
  );
};

export default City;
useGLTF.preload("/city.glb");
